version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.70
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
